// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	uuid "github.com/gofrs/uuid/v5"
)

// set field if value's pointer is not nil.
func (c *CommentUpdate) SetNotNilUpdatedAt(value *time.Time) *CommentUpdate {
	if value != nil {
		return c.SetUpdatedAt(*value)
	}
	return c
}

// set field if value's pointer is not nil.
func (c *CommentUpdateOne) SetNotNilUpdatedAt(value *time.Time) *CommentUpdateOne {
	if value != nil {
		return c.SetUpdatedAt(*value)
	}
	return c
}

// set field if value's pointer is not nil.
func (c *CommentCreate) SetNotNilUpdatedAt(value *time.Time) *CommentCreate {
	if value != nil {
		return c.SetUpdatedAt(*value)
	}
	return c
}

// set field if value's pointer is not nil.
func (c *CommentUpdate) SetNotNilTitle(value *string) *CommentUpdate {
	if value != nil {
		return c.SetTitle(*value)
	}
	return c
}

// set field if value's pointer is not nil.
func (c *CommentUpdateOne) SetNotNilTitle(value *string) *CommentUpdateOne {
	if value != nil {
		return c.SetTitle(*value)
	}
	return c
}

// set field if value's pointer is not nil.
func (c *CommentCreate) SetNotNilTitle(value *string) *CommentCreate {
	if value != nil {
		return c.SetTitle(*value)
	}
	return c
}

// set field if value's pointer is not nil.
func (c *CommentUpdate) SetNotNilContent(value *string) *CommentUpdate {
	if value != nil {
		return c.SetContent(*value)
	}
	return c
}

// set field if value's pointer is not nil.
func (c *CommentUpdateOne) SetNotNilContent(value *string) *CommentUpdateOne {
	if value != nil {
		return c.SetContent(*value)
	}
	return c
}

// set field if value's pointer is not nil.
func (c *CommentCreate) SetNotNilContent(value *string) *CommentCreate {
	if value != nil {
		return c.SetContent(*value)
	}
	return c
}

// set field if value's pointer is not nil.
func (c *CommentUpdate) SetNotNilMemberId(value *string) *CommentUpdate {
	if value != nil {
		return c.SetMemberId(*value)
	}
	return c
}

// set field if value's pointer is not nil.
func (c *CommentUpdateOne) SetNotNilMemberId(value *string) *CommentUpdateOne {
	if value != nil {
		return c.SetMemberId(*value)
	}
	return c
}

// set field if value's pointer is not nil.
func (c *CommentCreate) SetNotNilMemberId(value *string) *CommentCreate {
	if value != nil {
		return c.SetMemberId(*value)
	}
	return c
}

// set field if value's pointer is not nil.
func (c *CommentUpdate) SetNotNilCreateTime(value *time.Time) *CommentUpdate {
	if value != nil {
		return c.SetCreateTime(*value)
	}
	return c
}

// set field if value's pointer is not nil.
func (c *CommentUpdateOne) SetNotNilCreateTime(value *time.Time) *CommentUpdateOne {
	if value != nil {
		return c.SetCreateTime(*value)
	}
	return c
}

// set field if value's pointer is not nil.
func (c *CommentCreate) SetNotNilCreateTime(value *time.Time) *CommentCreate {
	if value != nil {
		return c.SetCreateTime(*value)
	}
	return c
}

// set field if value's pointer is not nil.
func (c *CommentUpdate) SetNotNilUpdateTime(value *time.Time) *CommentUpdate {
	if value != nil {
		return c.SetUpdateTime(*value)
	}
	return c
}

// set field if value's pointer is not nil.
func (c *CommentUpdateOne) SetNotNilUpdateTime(value *time.Time) *CommentUpdateOne {
	if value != nil {
		return c.SetUpdateTime(*value)
	}
	return c
}

// set field if value's pointer is not nil.
func (c *CommentCreate) SetNotNilUpdateTime(value *time.Time) *CommentCreate {
	if value != nil {
		return c.SetUpdateTime(*value)
	}
	return c
}

// set field if value's pointer is not nil.
func (c *CommentUpdate) SetNotNilIsReply(value *bool) *CommentUpdate {
	if value != nil {
		return c.SetIsReply(*value)
	}
	return c
}

// set field if value's pointer is not nil.
func (c *CommentUpdateOne) SetNotNilIsReply(value *bool) *CommentUpdateOne {
	if value != nil {
		return c.SetIsReply(*value)
	}
	return c
}

// set field if value's pointer is not nil.
func (c *CommentCreate) SetNotNilIsReply(value *bool) *CommentCreate {
	if value != nil {
		return c.SetIsReply(*value)
	}
	return c
}

// set field if value's pointer is not nil.
func (m *MemberUpdate) SetNotNilUpdatedAt(value *time.Time) *MemberUpdate {
	if value != nil {
		return m.SetUpdatedAt(*value)
	}
	return m
}

// set field if value's pointer is not nil.
func (m *MemberUpdateOne) SetNotNilUpdatedAt(value *time.Time) *MemberUpdateOne {
	if value != nil {
		return m.SetUpdatedAt(*value)
	}
	return m
}

// set field if value's pointer is not nil.
func (m *MemberCreate) SetNotNilUpdatedAt(value *time.Time) *MemberCreate {
	if value != nil {
		return m.SetUpdatedAt(*value)
	}
	return m
}

// set field if value's pointer is not nil.
func (m *MemberUpdate) SetNotNilStatus(value *uint8) *MemberUpdate {
	if value != nil {
		return m.SetStatus(*value)
	}
	return m
}

// set field if value's pointer is not nil.
func (m *MemberUpdateOne) SetNotNilStatus(value *uint8) *MemberUpdateOne {
	if value != nil {
		return m.SetStatus(*value)
	}
	return m
}

// set field if value's pointer is not nil.
func (m *MemberCreate) SetNotNilStatus(value *uint8) *MemberCreate {
	if value != nil {
		return m.SetStatus(*value)
	}
	return m
}

// set field if value's pointer is not nil.
func (m *MemberUpdate) SetNotNilForeinID(value *string) *MemberUpdate {
	if value != nil {
		return m.SetForeinID(*value)
	}
	return m
}

// set field if value's pointer is not nil.
func (m *MemberUpdateOne) SetNotNilForeinID(value *string) *MemberUpdateOne {
	if value != nil {
		return m.SetForeinID(*value)
	}
	return m
}

// set field if value's pointer is not nil.
func (m *MemberCreate) SetNotNilForeinID(value *string) *MemberCreate {
	if value != nil {
		return m.SetForeinID(*value)
	}
	return m
}

// set field if value's pointer is not nil.
func (m *MemberUpdate) SetNotNilUsername(value *string) *MemberUpdate {
	if value != nil {
		return m.SetUsername(*value)
	}
	return m
}

// set field if value's pointer is not nil.
func (m *MemberUpdateOne) SetNotNilUsername(value *string) *MemberUpdateOne {
	if value != nil {
		return m.SetUsername(*value)
	}
	return m
}

// set field if value's pointer is not nil.
func (m *MemberCreate) SetNotNilUsername(value *string) *MemberCreate {
	if value != nil {
		return m.SetUsername(*value)
	}
	return m
}

// set field if value's pointer is not nil.
func (m *MemberUpdate) SetNotNilPassword(value *string) *MemberUpdate {
	if value != nil {
		return m.SetPassword(*value)
	}
	return m
}

// set field if value's pointer is not nil.
func (m *MemberUpdateOne) SetNotNilPassword(value *string) *MemberUpdateOne {
	if value != nil {
		return m.SetPassword(*value)
	}
	return m
}

// set field if value's pointer is not nil.
func (m *MemberCreate) SetNotNilPassword(value *string) *MemberCreate {
	if value != nil {
		return m.SetPassword(*value)
	}
	return m
}

// set field if value's pointer is not nil.
func (m *MemberUpdate) SetNotNilNickname(value *string) *MemberUpdate {
	if value != nil {
		return m.SetNickname(*value)
	}
	return m
}

// set field if value's pointer is not nil.
func (m *MemberUpdateOne) SetNotNilNickname(value *string) *MemberUpdateOne {
	if value != nil {
		return m.SetNickname(*value)
	}
	return m
}

// set field if value's pointer is not nil.
func (m *MemberCreate) SetNotNilNickname(value *string) *MemberCreate {
	if value != nil {
		return m.SetNickname(*value)
	}
	return m
}

// set field if value's pointer is not nil.
func (m *MemberUpdate) SetNotNilRankID(value *uint64) *MemberUpdate {
	if value != nil {
		return m.SetRankID(*value)
	}
	return m
}

// set field if value's pointer is not nil.
func (m *MemberUpdateOne) SetNotNilRankID(value *uint64) *MemberUpdateOne {
	if value != nil {
		return m.SetRankID(*value)
	}
	return m
}

// set field if value's pointer is not nil.
func (m *MemberCreate) SetNotNilRankID(value *uint64) *MemberCreate {
	if value != nil {
		return m.SetRankID(*value)
	}
	return m
}

// set field if value's pointer is not nil.
func (m *MemberUpdate) SetNotNilMobile(value *string) *MemberUpdate {
	if value != nil {
		return m.SetMobile(*value)
	}
	return m
}

// set field if value's pointer is not nil.
func (m *MemberUpdateOne) SetNotNilMobile(value *string) *MemberUpdateOne {
	if value != nil {
		return m.SetMobile(*value)
	}
	return m
}

// set field if value's pointer is not nil.
func (m *MemberCreate) SetNotNilMobile(value *string) *MemberCreate {
	if value != nil {
		return m.SetMobile(*value)
	}
	return m
}

// set field if value's pointer is not nil.
func (m *MemberUpdate) SetNotNilEmail(value *string) *MemberUpdate {
	if value != nil {
		return m.SetEmail(*value)
	}
	return m
}

// set field if value's pointer is not nil.
func (m *MemberUpdateOne) SetNotNilEmail(value *string) *MemberUpdateOne {
	if value != nil {
		return m.SetEmail(*value)
	}
	return m
}

// set field if value's pointer is not nil.
func (m *MemberCreate) SetNotNilEmail(value *string) *MemberCreate {
	if value != nil {
		return m.SetEmail(*value)
	}
	return m
}

// set field if value's pointer is not nil.
func (m *MemberUpdate) SetNotNilGender(value *string) *MemberUpdate {
	if value != nil {
		return m.SetGender(*value)
	}
	return m
}

// set field if value's pointer is not nil.
func (m *MemberUpdateOne) SetNotNilGender(value *string) *MemberUpdateOne {
	if value != nil {
		return m.SetGender(*value)
	}
	return m
}

// set field if value's pointer is not nil.
func (m *MemberCreate) SetNotNilGender(value *string) *MemberCreate {
	if value != nil {
		return m.SetGender(*value)
	}
	return m
}

// set field if value's pointer is not nil.
func (m *MemberUpdate) SetNotNilBirthday(value *string) *MemberUpdate {
	if value != nil {
		return m.SetBirthday(*value)
	}
	return m
}

// set field if value's pointer is not nil.
func (m *MemberUpdateOne) SetNotNilBirthday(value *string) *MemberUpdateOne {
	if value != nil {
		return m.SetBirthday(*value)
	}
	return m
}

// set field if value's pointer is not nil.
func (m *MemberCreate) SetNotNilBirthday(value *string) *MemberCreate {
	if value != nil {
		return m.SetBirthday(*value)
	}
	return m
}

// set field if value's pointer is not nil.
func (m *MemberUpdate) SetNotNilAvatar(value *string) *MemberUpdate {
	if value != nil {
		return m.SetAvatar(*value)
	}
	return m
}

// set field if value's pointer is not nil.
func (m *MemberUpdateOne) SetNotNilAvatar(value *string) *MemberUpdateOne {
	if value != nil {
		return m.SetAvatar(*value)
	}
	return m
}

// set field if value's pointer is not nil.
func (m *MemberCreate) SetNotNilAvatar(value *string) *MemberCreate {
	if value != nil {
		return m.SetAvatar(*value)
	}
	return m
}

// set field if value's pointer is not nil.
func (m *MemberUpdate) SetNotNilWechatOpenID(value *string) *MemberUpdate {
	if value != nil {
		return m.SetWechatOpenID(*value)
	}
	return m
}

// set field if value's pointer is not nil.
func (m *MemberUpdateOne) SetNotNilWechatOpenID(value *string) *MemberUpdateOne {
	if value != nil {
		return m.SetWechatOpenID(*value)
	}
	return m
}

// set field if value's pointer is not nil.
func (m *MemberCreate) SetNotNilWechatOpenID(value *string) *MemberCreate {
	if value != nil {
		return m.SetWechatOpenID(*value)
	}
	return m
}

// set field if value's pointer is not nil.
func (m *MemberUpdate) SetNotNilExpiredAt(value *time.Time) *MemberUpdate {
	if value != nil {
		return m.SetExpiredAt(*value)
	}
	return m
}

// set field if value's pointer is not nil.
func (m *MemberUpdateOne) SetNotNilExpiredAt(value *time.Time) *MemberUpdateOne {
	if value != nil {
		return m.SetExpiredAt(*value)
	}
	return m
}

// set field if value's pointer is not nil.
func (m *MemberCreate) SetNotNilExpiredAt(value *time.Time) *MemberCreate {
	if value != nil {
		return m.SetExpiredAt(*value)
	}
	return m
}

// set field if value's pointer is not nil.
func (mr *MemberRankUpdate) SetNotNilUpdatedAt(value *time.Time) *MemberRankUpdate {
	if value != nil {
		return mr.SetUpdatedAt(*value)
	}
	return mr
}

// set field if value's pointer is not nil.
func (mr *MemberRankUpdateOne) SetNotNilUpdatedAt(value *time.Time) *MemberRankUpdateOne {
	if value != nil {
		return mr.SetUpdatedAt(*value)
	}
	return mr
}

// set field if value's pointer is not nil.
func (mr *MemberRankCreate) SetNotNilUpdatedAt(value *time.Time) *MemberRankCreate {
	if value != nil {
		return mr.SetUpdatedAt(*value)
	}
	return mr
}

// set field if value's pointer is not nil.
func (mr *MemberRankUpdate) SetNotNilName(value *string) *MemberRankUpdate {
	if value != nil {
		return mr.SetName(*value)
	}
	return mr
}

// set field if value's pointer is not nil.
func (mr *MemberRankUpdateOne) SetNotNilName(value *string) *MemberRankUpdateOne {
	if value != nil {
		return mr.SetName(*value)
	}
	return mr
}

// set field if value's pointer is not nil.
func (mr *MemberRankCreate) SetNotNilName(value *string) *MemberRankCreate {
	if value != nil {
		return mr.SetName(*value)
	}
	return mr
}

// set field if value's pointer is not nil.
func (mr *MemberRankUpdate) SetNotNilCode(value *string) *MemberRankUpdate {
	if value != nil {
		return mr.SetCode(*value)
	}
	return mr
}

// set field if value's pointer is not nil.
func (mr *MemberRankUpdateOne) SetNotNilCode(value *string) *MemberRankUpdateOne {
	if value != nil {
		return mr.SetCode(*value)
	}
	return mr
}

// set field if value's pointer is not nil.
func (mr *MemberRankCreate) SetNotNilCode(value *string) *MemberRankCreate {
	if value != nil {
		return mr.SetCode(*value)
	}
	return mr
}

// set field if value's pointer is not nil.
func (mr *MemberRankUpdate) SetNotNilDescription(value *string) *MemberRankUpdate {
	if value != nil {
		return mr.SetDescription(*value)
	}
	return mr
}

// set field if value's pointer is not nil.
func (mr *MemberRankUpdateOne) SetNotNilDescription(value *string) *MemberRankUpdateOne {
	if value != nil {
		return mr.SetDescription(*value)
	}
	return mr
}

// set field if value's pointer is not nil.
func (mr *MemberRankCreate) SetNotNilDescription(value *string) *MemberRankCreate {
	if value != nil {
		return mr.SetDescription(*value)
	}
	return mr
}

// set field if value's pointer is not nil.
func (mr *MemberRankUpdate) SetNotNilRemark(value *string) *MemberRankUpdate {
	if value != nil {
		return mr.SetRemark(*value)
	}
	return mr
}

// set field if value's pointer is not nil.
func (mr *MemberRankUpdateOne) SetNotNilRemark(value *string) *MemberRankUpdateOne {
	if value != nil {
		return mr.SetRemark(*value)
	}
	return mr
}

// set field if value's pointer is not nil.
func (mr *MemberRankCreate) SetNotNilRemark(value *string) *MemberRankCreate {
	if value != nil {
		return mr.SetRemark(*value)
	}
	return mr
}

// set field if value's pointer is not nil.
func (op *OauthProviderUpdate) SetNotNilUpdatedAt(value *time.Time) *OauthProviderUpdate {
	if value != nil {
		return op.SetUpdatedAt(*value)
	}
	return op
}

// set field if value's pointer is not nil.
func (op *OauthProviderUpdateOne) SetNotNilUpdatedAt(value *time.Time) *OauthProviderUpdateOne {
	if value != nil {
		return op.SetUpdatedAt(*value)
	}
	return op
}

// set field if value's pointer is not nil.
func (op *OauthProviderCreate) SetNotNilUpdatedAt(value *time.Time) *OauthProviderCreate {
	if value != nil {
		return op.SetUpdatedAt(*value)
	}
	return op
}

// set field if value's pointer is not nil.
func (op *OauthProviderUpdate) SetNotNilName(value *string) *OauthProviderUpdate {
	if value != nil {
		return op.SetName(*value)
	}
	return op
}

// set field if value's pointer is not nil.
func (op *OauthProviderUpdateOne) SetNotNilName(value *string) *OauthProviderUpdateOne {
	if value != nil {
		return op.SetName(*value)
	}
	return op
}

// set field if value's pointer is not nil.
func (op *OauthProviderCreate) SetNotNilName(value *string) *OauthProviderCreate {
	if value != nil {
		return op.SetName(*value)
	}
	return op
}

// set field if value's pointer is not nil.
func (op *OauthProviderUpdate) SetNotNilClientID(value *string) *OauthProviderUpdate {
	if value != nil {
		return op.SetClientID(*value)
	}
	return op
}

// set field if value's pointer is not nil.
func (op *OauthProviderUpdateOne) SetNotNilClientID(value *string) *OauthProviderUpdateOne {
	if value != nil {
		return op.SetClientID(*value)
	}
	return op
}

// set field if value's pointer is not nil.
func (op *OauthProviderCreate) SetNotNilClientID(value *string) *OauthProviderCreate {
	if value != nil {
		return op.SetClientID(*value)
	}
	return op
}

// set field if value's pointer is not nil.
func (op *OauthProviderUpdate) SetNotNilClientSecret(value *string) *OauthProviderUpdate {
	if value != nil {
		return op.SetClientSecret(*value)
	}
	return op
}

// set field if value's pointer is not nil.
func (op *OauthProviderUpdateOne) SetNotNilClientSecret(value *string) *OauthProviderUpdateOne {
	if value != nil {
		return op.SetClientSecret(*value)
	}
	return op
}

// set field if value's pointer is not nil.
func (op *OauthProviderCreate) SetNotNilClientSecret(value *string) *OauthProviderCreate {
	if value != nil {
		return op.SetClientSecret(*value)
	}
	return op
}

// set field if value's pointer is not nil.
func (op *OauthProviderUpdate) SetNotNilRedirectURL(value *string) *OauthProviderUpdate {
	if value != nil {
		return op.SetRedirectURL(*value)
	}
	return op
}

// set field if value's pointer is not nil.
func (op *OauthProviderUpdateOne) SetNotNilRedirectURL(value *string) *OauthProviderUpdateOne {
	if value != nil {
		return op.SetRedirectURL(*value)
	}
	return op
}

// set field if value's pointer is not nil.
func (op *OauthProviderCreate) SetNotNilRedirectURL(value *string) *OauthProviderCreate {
	if value != nil {
		return op.SetRedirectURL(*value)
	}
	return op
}

// set field if value's pointer is not nil.
func (op *OauthProviderUpdate) SetNotNilScopes(value *string) *OauthProviderUpdate {
	if value != nil {
		return op.SetScopes(*value)
	}
	return op
}

// set field if value's pointer is not nil.
func (op *OauthProviderUpdateOne) SetNotNilScopes(value *string) *OauthProviderUpdateOne {
	if value != nil {
		return op.SetScopes(*value)
	}
	return op
}

// set field if value's pointer is not nil.
func (op *OauthProviderCreate) SetNotNilScopes(value *string) *OauthProviderCreate {
	if value != nil {
		return op.SetScopes(*value)
	}
	return op
}

// set field if value's pointer is not nil.
func (op *OauthProviderUpdate) SetNotNilAuthURL(value *string) *OauthProviderUpdate {
	if value != nil {
		return op.SetAuthURL(*value)
	}
	return op
}

// set field if value's pointer is not nil.
func (op *OauthProviderUpdateOne) SetNotNilAuthURL(value *string) *OauthProviderUpdateOne {
	if value != nil {
		return op.SetAuthURL(*value)
	}
	return op
}

// set field if value's pointer is not nil.
func (op *OauthProviderCreate) SetNotNilAuthURL(value *string) *OauthProviderCreate {
	if value != nil {
		return op.SetAuthURL(*value)
	}
	return op
}

// set field if value's pointer is not nil.
func (op *OauthProviderUpdate) SetNotNilTokenURL(value *string) *OauthProviderUpdate {
	if value != nil {
		return op.SetTokenURL(*value)
	}
	return op
}

// set field if value's pointer is not nil.
func (op *OauthProviderUpdateOne) SetNotNilTokenURL(value *string) *OauthProviderUpdateOne {
	if value != nil {
		return op.SetTokenURL(*value)
	}
	return op
}

// set field if value's pointer is not nil.
func (op *OauthProviderCreate) SetNotNilTokenURL(value *string) *OauthProviderCreate {
	if value != nil {
		return op.SetTokenURL(*value)
	}
	return op
}

// set field if value's pointer is not nil.
func (op *OauthProviderUpdate) SetNotNilAuthStyle(value *uint64) *OauthProviderUpdate {
	if value != nil {
		return op.SetAuthStyle(*value)
	}
	return op
}

// set field if value's pointer is not nil.
func (op *OauthProviderUpdateOne) SetNotNilAuthStyle(value *uint64) *OauthProviderUpdateOne {
	if value != nil {
		return op.SetAuthStyle(*value)
	}
	return op
}

// set field if value's pointer is not nil.
func (op *OauthProviderCreate) SetNotNilAuthStyle(value *uint64) *OauthProviderCreate {
	if value != nil {
		return op.SetAuthStyle(*value)
	}
	return op
}

// set field if value's pointer is not nil.
func (op *OauthProviderUpdate) SetNotNilInfoURL(value *string) *OauthProviderUpdate {
	if value != nil {
		return op.SetInfoURL(*value)
	}
	return op
}

// set field if value's pointer is not nil.
func (op *OauthProviderUpdateOne) SetNotNilInfoURL(value *string) *OauthProviderUpdateOne {
	if value != nil {
		return op.SetInfoURL(*value)
	}
	return op
}

// set field if value's pointer is not nil.
func (op *OauthProviderCreate) SetNotNilInfoURL(value *string) *OauthProviderCreate {
	if value != nil {
		return op.SetInfoURL(*value)
	}
	return op
}

// set field if value's pointer is not nil.
func (r *ReplyUpdate) SetNotNilUpdatedAt(value *time.Time) *ReplyUpdate {
	if value != nil {
		return r.SetUpdatedAt(*value)
	}
	return r
}

// set field if value's pointer is not nil.
func (r *ReplyUpdateOne) SetNotNilUpdatedAt(value *time.Time) *ReplyUpdateOne {
	if value != nil {
		return r.SetUpdatedAt(*value)
	}
	return r
}

// set field if value's pointer is not nil.
func (r *ReplyCreate) SetNotNilUpdatedAt(value *time.Time) *ReplyCreate {
	if value != nil {
		return r.SetUpdatedAt(*value)
	}
	return r
}

// set field if value's pointer is not nil.
func (r *ReplyUpdate) SetNotNilCommentID(value *uint64) *ReplyUpdate {
	if value != nil {
		return r.SetCommentID(*value)
	}
	return r
}

// set field if value's pointer is not nil.
func (r *ReplyUpdateOne) SetNotNilCommentID(value *uint64) *ReplyUpdateOne {
	if value != nil {
		return r.SetCommentID(*value)
	}
	return r
}

// set field if value's pointer is not nil.
func (r *ReplyCreate) SetNotNilCommentID(value *uint64) *ReplyCreate {
	if value != nil {
		return r.SetCommentID(*value)
	}
	return r
}

// set field if value's pointer is not nil.
func (r *ReplyUpdate) SetNotNilReply(value *string) *ReplyUpdate {
	if value != nil {
		return r.SetReply(*value)
	}
	return r
}

// set field if value's pointer is not nil.
func (r *ReplyUpdateOne) SetNotNilReply(value *string) *ReplyUpdateOne {
	if value != nil {
		return r.SetReply(*value)
	}
	return r
}

// set field if value's pointer is not nil.
func (r *ReplyCreate) SetNotNilReply(value *string) *ReplyCreate {
	if value != nil {
		return r.SetReply(*value)
	}
	return r
}

// set field if value's pointer is not nil.
func (r *ReplyUpdate) SetNotNilAdminId(value *string) *ReplyUpdate {
	if value != nil {
		return r.SetAdminId(*value)
	}
	return r
}

// set field if value's pointer is not nil.
func (r *ReplyUpdateOne) SetNotNilAdminId(value *string) *ReplyUpdateOne {
	if value != nil {
		return r.SetAdminId(*value)
	}
	return r
}

// set field if value's pointer is not nil.
func (r *ReplyCreate) SetNotNilAdminId(value *string) *ReplyCreate {
	if value != nil {
		return r.SetAdminId(*value)
	}
	return r
}

// set field if value's pointer is not nil.
func (r *ReplyUpdate) SetNotNilAdminName(value *string) *ReplyUpdate {
	if value != nil {
		return r.SetAdminName(*value)
	}
	return r
}

// set field if value's pointer is not nil.
func (r *ReplyUpdateOne) SetNotNilAdminName(value *string) *ReplyUpdateOne {
	if value != nil {
		return r.SetAdminName(*value)
	}
	return r
}

// set field if value's pointer is not nil.
func (r *ReplyCreate) SetNotNilAdminName(value *string) *ReplyCreate {
	if value != nil {
		return r.SetAdminName(*value)
	}
	return r
}

// set field if value's pointer is not nil.
func (r *ReplyUpdate) SetNotNilCreateTime(value *time.Time) *ReplyUpdate {
	if value != nil {
		return r.SetCreateTime(*value)
	}
	return r
}

// set field if value's pointer is not nil.
func (r *ReplyUpdateOne) SetNotNilCreateTime(value *time.Time) *ReplyUpdateOne {
	if value != nil {
		return r.SetCreateTime(*value)
	}
	return r
}

// set field if value's pointer is not nil.
func (r *ReplyCreate) SetNotNilCreateTime(value *time.Time) *ReplyCreate {
	if value != nil {
		return r.SetCreateTime(*value)
	}
	return r
}

// set field if value's pointer is not nil.
func (r *ReplyUpdate) SetNotNilUpdateTime(value *time.Time) *ReplyUpdate {
	if value != nil {
		return r.SetUpdateTime(*value)
	}
	return r
}

// set field if value's pointer is not nil.
func (r *ReplyUpdateOne) SetNotNilUpdateTime(value *time.Time) *ReplyUpdateOne {
	if value != nil {
		return r.SetUpdateTime(*value)
	}
	return r
}

// set field if value's pointer is not nil.
func (r *ReplyCreate) SetNotNilUpdateTime(value *time.Time) *ReplyCreate {
	if value != nil {
		return r.SetUpdateTime(*value)
	}
	return r
}

// set field if value's pointer is not nil.
func (t *TokenUpdate) SetNotNilUpdatedAt(value *time.Time) *TokenUpdate {
	if value != nil {
		return t.SetUpdatedAt(*value)
	}
	return t
}

// set field if value's pointer is not nil.
func (t *TokenUpdateOne) SetNotNilUpdatedAt(value *time.Time) *TokenUpdateOne {
	if value != nil {
		return t.SetUpdatedAt(*value)
	}
	return t
}

// set field if value's pointer is not nil.
func (t *TokenCreate) SetNotNilUpdatedAt(value *time.Time) *TokenCreate {
	if value != nil {
		return t.SetUpdatedAt(*value)
	}
	return t
}

// set field if value's pointer is not nil.
func (t *TokenUpdate) SetNotNilStatus(value *uint8) *TokenUpdate {
	if value != nil {
		return t.SetStatus(*value)
	}
	return t
}

// set field if value's pointer is not nil.
func (t *TokenUpdateOne) SetNotNilStatus(value *uint8) *TokenUpdateOne {
	if value != nil {
		return t.SetStatus(*value)
	}
	return t
}

// set field if value's pointer is not nil.
func (t *TokenCreate) SetNotNilStatus(value *uint8) *TokenCreate {
	if value != nil {
		return t.SetStatus(*value)
	}
	return t
}

// set field if value's pointer is not nil.
func (t *TokenUpdate) SetNotNilUUID(value *uuid.UUID) *TokenUpdate {
	if value != nil {
		return t.SetUUID(*value)
	}
	return t
}

// set field if value's pointer is not nil.
func (t *TokenUpdateOne) SetNotNilUUID(value *uuid.UUID) *TokenUpdateOne {
	if value != nil {
		return t.SetUUID(*value)
	}
	return t
}

// set field if value's pointer is not nil.
func (t *TokenCreate) SetNotNilUUID(value *uuid.UUID) *TokenCreate {
	if value != nil {
		return t.SetUUID(*value)
	}
	return t
}

// set field if value's pointer is not nil.
func (t *TokenUpdate) SetNotNilToken(value *string) *TokenUpdate {
	if value != nil {
		return t.SetToken(*value)
	}
	return t
}

// set field if value's pointer is not nil.
func (t *TokenUpdateOne) SetNotNilToken(value *string) *TokenUpdateOne {
	if value != nil {
		return t.SetToken(*value)
	}
	return t
}

// set field if value's pointer is not nil.
func (t *TokenCreate) SetNotNilToken(value *string) *TokenCreate {
	if value != nil {
		return t.SetToken(*value)
	}
	return t
}

// set field if value's pointer is not nil.
func (t *TokenUpdate) SetNotNilUsername(value *string) *TokenUpdate {
	if value != nil {
		return t.SetUsername(*value)
	}
	return t
}

// set field if value's pointer is not nil.
func (t *TokenUpdateOne) SetNotNilUsername(value *string) *TokenUpdateOne {
	if value != nil {
		return t.SetUsername(*value)
	}
	return t
}

// set field if value's pointer is not nil.
func (t *TokenCreate) SetNotNilUsername(value *string) *TokenCreate {
	if value != nil {
		return t.SetUsername(*value)
	}
	return t
}

// set field if value's pointer is not nil.
func (t *TokenUpdate) SetNotNilSource(value *string) *TokenUpdate {
	if value != nil {
		return t.SetSource(*value)
	}
	return t
}

// set field if value's pointer is not nil.
func (t *TokenUpdateOne) SetNotNilSource(value *string) *TokenUpdateOne {
	if value != nil {
		return t.SetSource(*value)
	}
	return t
}

// set field if value's pointer is not nil.
func (t *TokenCreate) SetNotNilSource(value *string) *TokenCreate {
	if value != nil {
		return t.SetSource(*value)
	}
	return t
}

// set field if value's pointer is not nil.
func (t *TokenUpdate) SetNotNilExpiredAt(value *time.Time) *TokenUpdate {
	if value != nil {
		return t.SetExpiredAt(*value)
	}
	return t
}

// set field if value's pointer is not nil.
func (t *TokenUpdateOne) SetNotNilExpiredAt(value *time.Time) *TokenUpdateOne {
	if value != nil {
		return t.SetExpiredAt(*value)
	}
	return t
}

// set field if value's pointer is not nil.
func (t *TokenCreate) SetNotNilExpiredAt(value *time.Time) *TokenCreate {
	if value != nil {
		return t.SetExpiredAt(*value)
	}
	return t
}
